program: scripts/train_vlp.py
method: grid
metric:
  name: best_val_loss
  goal: minimize
parameters:
  batch_size:
    value: 250
  learning_rate:
    value: 1e-4
  dropout:
    value: 0.2
  accumulate_steps:
    value: 2
  seed:
    value: 42
